version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=us-east-1
      - VANTA_API_KEY=${VANTA_API_KEY}
      - VANTA_API_BASE_URL=https://api.vanta.com/v1
      - APP_NAME=FinTrust AI
      - APP_VERSION=1.0.0
      - DEBUG=True
      - SECRET_KEY=your-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - S3_BUCKET_NAME=fintrust-ai-reports
      - KMS_KEY_ID=alias/fintrust-ai-key
      - CLOUDWATCH_LOG_GROUP=fintrust-ai-logs
    volumes:
      - ../backend:/app
    depends_on:
      - redis
    networks:
      - fintrust-network

  # Frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - fintrust-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fintrust-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - fintrust-network

volumes:
  redis_data:

networks:
  fintrust-network:
    driver: bridge
